#!/usr/bin/env python3
"""Build docs/h3/matrix.md from OE summaries and tournament inventory."""

from __future__ import annotations

import json

from paths import DOCS_H3_MATRIX, H3_LAYOUTS_OE

TOURNAMENT = [
    ("h3dm1", "L-U mirror", "Symmetry / h3-port", "missing"),
    ("mt_Diamond", "L-U mirror", "Fair'n Square / h3-port", "missing"),
    ("mt_Jebus", "L-U mirror", "Jebus Cross Classic / h3-port", "partial"),
    ("mt_TeamJebus", "L-U mirror 2v2", "OctoJebus / h3-port", "partial"),
    ("mt_Andromeda", "XL-U mirror", "Universe / h3-port", "missing"),
    ("mt_Antares", "L-U mirror", "Spider / h3-port", "missing"),
    ("mt_Firewalk", "XL-U mirror", "Firewalk / h3-port", "missing"),
    ("6lm10a", "XL+U", "Spider / h3-port", "missing"),
    ("8mm6a", "XL+U", "Crossroads / h3-port", "missing"),
    ("8xm12a", "XL+U", "Expanse / h3-port", "missing"),
    ("Spider", "XL+U", "Spider.rmg.json", "matched"),
    ("Nostalgia", "XL+U", "Mini-Nostalgia / h3-port Nostalgia", "partial"),
    ("Kerberos", "XL+U 2-3p", "Kerberos.rmg.json", "partial"),
    ("Clash of Dragons", "XL+U", "Anarchy / h3-port", "partial"),
    ("Firewalk", "XL+U", "Jebus Cross / h3-port", "partial"),
    ("Jebus Cross", "XL-U", "Jebus Cross.rmg.json", "matched"),
    ("2sm4d(3)", "L+U", "Diamond / h3-port", "missing"),
    ("Mini-Nostalgia", "L+U", "Mini-Nostalgia.rmg.json", "matched"),
    ("Diamond", "L+U", "Diamond.rmg.json", "matched"),
    ("Boomerang", "L+U", "Mini-Nostalgia / h3-port", "missing"),
    ("Apocalypse", "L+U", "Diamond / h3-port", "missing"),
    ("Anarchy", "L+U 12 variants", "Anarchy.rmg.json", "partial"),
    ("Black'n'Blue", "L+U", "Jebus Cross Classic / h3-port", "missing"),
    ("2sm2c(2)", "M-U 200%", "Blitz / h3-port", "missing"),
    ("Skirmish(M)", "M-U 200%", "Blitz / h3-port", "missing"),
    ("Nine-day Wonder", "M-U 200%", "Sprint / h3-port", "missing"),
]


def oe_lookup(index: list[dict], file_name: str) -> dict | None:
    for item in index:
        if item["file"] == file_name:
            return item
    return None


def main() -> int:
    oe_index_path = H3_LAYOUTS_OE / "_index.json"
    index = json.loads(oe_index_path.read_text(encoding="utf-8"))

    lines = [
        "# H3 HotA Tournament ↔ Olden Era Template Matrix",
        "",
        "> Auto-generated by `tools/build_h3_oe_matrix.py`. Do not edit by hand.",
        "",
        "Cross-reference of [h3hota.com tournament templates](https://h3hota.com/en/rules#template-rules)",
        "against OE [`templates/`](../templates/) and scaffolded [`templates/h3-port/`](../templates/h3-port/).",
        "",
        "Legend: **matched** = direct OE ship; **partial** = name match with topology/size/rule gaps; **missing** = scaffold only in h3-port.",
        "",
        "## Tournament inventory",
        "",
        "| H3 template | H3 size | OE target | Match |",
        "|-------------|---------|-----------|-------|",
    ]
    for name, h3_size, oe_target, status in TOURNAMENT:
        lines.append(f"| {name} | {h3_size} | {oe_target} | {status} |")

    lines += [
        "",
        "## Tier 1 audit",
        "",
        f"See [`tier1-audit.md`](tier1-audit.md) for human gap analysis of direct-name OE matches.",
        "",
        "## H3 reference sources",
        "",
        "- Rules & lobby settings: https://h3hota.com/en/rules",
        "- Layout notation & descriptions: https://h3hota.com/en/templates",
        "- Template format: https://h3hota.com/en/template-format",
        f"- Official `.h3t` packs: [`h3/sources/official/`](../../h3/sources/official/)",
        f"- Parsed topology JSON: [`h3/layouts/official/`](../../h3/layouts/official/)",
        f"- OE topology summaries: [`h3/layouts/oe/`](../../h3/layouts/oe/)",
        f"- Download catalog: [`catalog.md`](catalog.md)",
        "",
    ]
    DOCS_H3_MATRIX.parent.mkdir(parents=True, exist_ok=True)
    DOCS_H3_MATRIX.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {DOCS_H3_MATRIX}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
