#!/usr/bin/env python3
"""Parse all official HotA tournament .h3t packs and emit comparison index."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

from paths import (
    H3_LAYOUTS_OFFICIAL,
    H3_LAYOUTS_OE,
    H3_SOURCES_OFFICIAL,
    H3T_PARSER,
    HOTA_INSTALL,
)

TIER1 = {
    "Jebus Cross": "Jebus Cross.rmg.json",
    "Diamond": "Diamond.rmg.json",
    "Mini-Nostalgia": "Mini-Nostalgia.rmg.json",
    "Spider": "Spider.rmg.json",
    "Kerberos": "Kerberos.rmg.json",
    "Anarchy": "Anarchy.rmg.json",
    "Jebus Outcast": "Jebus Outcast.rmg.json",
}


def load_json(p: Path) -> dict:
    return json.loads(p.read_text(encoding="utf-8-sig"))


def main() -> int:
    H3_LAYOUTS_OFFICIAL.mkdir(parents=True, exist_ok=True)
    rows = []

    for h3t in sorted(H3_SOURCES_OFFICIAL.glob("*.h3t")):
        out = H3_LAYOUTS_OFFICIAL / f"{h3t.stem}.topology.json"
        subprocess.run([sys.executable, str(H3T_PARSER), str(h3t), str(out)], check=True)
        h3 = load_json(out)
        oe_file = TIER1.get(h3["pack_name"])
        oe_summary = None
        if oe_file:
            oe_path = H3_LAYOUTS_OE / f"{Path(oe_file).stem}.summary.json"
            if oe_path.exists():
                oe_summary = load_json(oe_path)
        rows.append({
            "h3_name": h3["pack_name"],
            "h3_zones": h3["zone_count"],
            "h3_connections": h3["connection_count"],
            "h3_mirror": any(m.get("mirror") for m in h3.get("maps", [])),
            "h3_pg_guards": sorted({
                c["guard_value"] for c in h3["connections"]
                if c.get("guard_value") and c["guard_value"] >= 10000
            }, reverse=True)[:5],
            "oe_file": oe_file,
            "oe_zones": oe_summary["variants"][0]["zone_count"] if oe_summary else None,
            "oe_connections": len(oe_summary["variants"][0]["connections"]) if oe_summary else None,
        })

    index_path = H3_LAYOUTS_OFFICIAL / "_index.json"
    index_path.write_text(json.dumps(rows, indent=2), encoding="utf-8")

    md = [
        "# Official HotA Tournament Topology Index",
        "",
        "> Auto-generated by `tools/parse_official_h3.py`. Do not edit by hand.",
        "",
        f"Source install: `{HOTA_INSTALL}`",
        "",
        "| H3 template | Zones | Conns | Mirror | PG guards | OE match | OE zones | OE conns |",
        "|-------------|-------|-------|--------|-----------|----------|----------|----------|",
    ]
    for r in rows:
        md.append(
            f"| {r['h3_name']} | {r['h3_zones']} | {r['h3_connections']} | "
            f"{'yes' if r['h3_mirror'] else 'no'} | {r['h3_pg_guards'] or '-'} | "
            f"{r['oe_file'] or '-'} | {r['oe_zones'] or '-'} | {r['oe_connections'] or '-'} |"
        )
    (H3_LAYOUTS_OFFICIAL / "README.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    print(f"Parsed {len(rows)} official templates -> {H3_LAYOUTS_OFFICIAL}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
